repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.26.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
