name: Common Jobs

on:
  workflow_call:
    outputs:
      tag:
        description: "The output file name"
        value: ${{ jobs.vars.outputs.tag }}
      repository:
        description: "The repository name"
        value: ${{ jobs.vars.outputs.repository }}

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      repository: ${{ steps.vars.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "tag=${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repository=us-central1-docker.pkg.dev/cdip-78ca/gundi-dispatchers/traptagger" >> $GITHUB_OUTPUT

  run_unit_tests:
    runs-on: ubuntu-latest
    needs: [vars]
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Install pip
        run: python -m ensurepip --upgrade

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest
        env:
          TRACING_ENABLED: ${{ vars.TRACING_ENABLED }}