name: Build the application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      repository:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - uses: actions/checkout@v3
    - id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}
    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: us-central1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        file: docker/Dockerfile
        tags: "${{ inputs.repository }}:${{ inputs.tag }}"