name: Build the application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      chart_repository:
        required: false
        type: string
        default: oci://us-central1-docker.pkg.dev/cdip-78ca/gundi-helm-charts
      chart_name:
        required: true
        type: string
      chart_version:
        required: true
        type: string
      repository:
        required: true
        type: string
      tag:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: application
    secrets:
      slack_webhook_url:
        required: true

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      # url: https://${{ inputs.subdomain }}.${{ inputs.https_domain }}
    
    steps:
    - uses: actions/checkout@v3
    - uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}
    - uses: 'google-github-actions/setup-gcloud@v1'
    - uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ vars.GKE_CLUTER_NAME }}
        location: 'us-central1'
    - uses: azure/setup-helm@v3
      with:
          version: 'v3.12.0'
    - run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        helm upgrade --install --create-namespace \
        ${{ inputs.chart_name }} ${{ inputs.chart_repository}}/${{ inputs.chart_name }} \
        --version ${{ inputs.chart_version }} \
        --namespace ${{ inputs.namespace }} \
        --set image.repository=${{ inputs.repository }} \
        --set image.tag=${{ inputs.tag }} \
        -f ./.github/workflows/values/${{ inputs.environment }}.yml

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
