name: PR Pipeline
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile

jobs:
  common:
    uses: ./.github/workflows/_dispatcher_common.yml
    with: 
      app_name: ${{ inputs.app_name }}
