name: Dispatcher Pipeline Zip
on:
  workflow_call:
    inputs:
      artifact_name: 
        type: string
        default: ""
      run_tests:
        type: boolean
        default: false
      deploy:
        type: boolean
        default: false
      environment:
        type: string
        default: "dev"
      secret_name: 
        type: string
        default: ""      
      secret_key: 
        type: string
        default: "deployment_settings.source_code_path"
    outputs:
      file_name: 
        description: "File name"
        value: ${{ jobs.vars.outputs.file_name }}

env:
  TRACING_ENABLED: ${{secrets.TRACING_ENABLED}}

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      file_name: ${{ steps.vars.outputs.file_name }}
    steps:
      - uses: actions/checkout@v4
      - id: vars
        run: |
          echo "file_name=${{ inputs.artifact_name }}-${{ github.head_ref || github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Checkout branch
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Install pip
        run: python -m ensurepip --upgrade

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest
        env:
          TRACING_ENABLED: ${{ secrets.TRACING_ENABLED }}

  zip:
    if: ${{ inputs.deploy }}
    uses: ./.github/workflows/zip_files.yml
    needs: [vars, test]
    with:
      input_files: "*"
      output_file: ${{ needs.vars.outputs.file_name }}

  upload:
    if: ${{ inputs.deploy }}
    uses: ./.github/workflows/upload_to_gcs.yml
    needs: [vars, zip]
    with:
      environment: ${{ inputs.environment }}
      file_name: ${{ needs.vars.outputs.file_name }}