name: PR Pipeline
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      python_version:
        description: Python version used to install requirements and run pytest
        type: string
        required: false
        default: '3.8'
      dockerfile:
        required: false
        type: string
        default: Dockerfile

jobs:
  common:
    uses: ./.github/workflows/_dispatcher_common.yml
    with:
      app_name: ${{ inputs.app_name }}
      python_version: ${{ inputs.python_version }}
