name: Release Pipeline
on:
  workflow_call:
    inputs:
      secret_name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      stage_environment:
        required: false
        type: string
        default: stage
      prod_environment:
        required: false
        type: string
        default: prod

jobs:
  common:
    uses: ./.github/workflows/_dispatcher_common.yml

  build:
    uses: ./.github/workflows/build_docker.yml
    needs: [common]
    with:
      environment: dev
      repository: ${{ needs.common.outputs.repository }}
      tag: ${{ needs.common.outputs.tag }}
      dockerfile: ${{ inputs.dockerfile }}

  update_secret_stage:
    uses: ./.github/workflows/update_json_secret_key.yml
    needs: [common, build]
    with:
      environment: ${{ inputs.stage_environment }}
      secret_name: "${{ inputs.secret_name }}-${{ inputs.stage_environment }}"
      secret_key: "deployment_settings.docker_image_url"
      secret_value: "${{ needs.common.outputs.repository }}:${{ needs.common.outputs.tag }}"

  update_secret_prod:
    uses: ./.github/workflows/update_json_secret_key.yml
    needs: [common, build, update_secret_stage]
    with:
      environment: ${{ inputs.prod_environment }}
      secret_name: "${{ inputs.secret_name }}-${{ inputs.prod_environment }}"
      secret_key: "deployment_settings.docker_image_url"
      secret_value: "${{ needs.common.outputs.repository }}:${{ needs.common.outputs.tag }}"
