name: Publish helm chart

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: europe-west3-docker.pkg.dev
      repository:
        required: false
        type: string
        default: padas-app/er-mt-helm
      chart_name:
        required: true
        type: string

jobs:
  publish:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4
    - uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.SERVICE_ACCOUNT }}
    - uses: 'google-github-actions/setup-gcloud@v2'
    - uses: azure/setup-helm@v4
      with:
          version: 'v3.13.1'
    - run: |
        gcloud auth configure-docker ${{ inputs.registry }}
        helm package ${{ inputs.chart_name }}
        echo "=== DEBUG: Files after packaging ==="
        ls -la ${{ inputs.chart_name }}-*
        echo "=== DEBUG: Push command ==="
        echo "helm push ${{ inputs.chart_name }}-* oci://${{ inputs.registry }}/${{ inputs.repository }}"
        echo "=== DEBUG: Expanded files ==="
        echo ${{ inputs.chart_name }}-*
        helm push ${{ inputs.chart_name }}-*.tgz oci://${{ inputs.registry }}/${{ inputs.repository }}

