name: 'Dev - Terragrunt GitHub Actions'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_dir:
        required: true
        type: string
      tg_command:
        required: true
        type: string
      tf_version:
        type: string
        default: '1.5.7'
      tg_version:
        type: string
        default: '0.54.8'

jobs:
  plan:
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}
          tg_dir: ${{ inputs.working_dir }}
          tg_command: ${{ inputs.tg_command }}
        env:
          INPUT_PRE_EXEC_1: |
            git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "ssh://git@github.com"

