name: 'Terraform GitHub Actions'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_dir:
        required: true
        type: string
      tf_command:
        required: true
        type: string
      tf_version:
        type: string
        default: '1.9.1'

jobs:
  terraform:
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.tf_version }}
      
      - run: terraform -chdir=${{ inputs.working_dir }} init
      - name: 'run terraform'
        run: |
          terraform -chdir=${{ inputs.working_dir }} ${{ inputs.tf_command }}
