name: Update GCP Secret

on:
  workflow_call:
    inputs:
      secret_name:
        description: 'GCP Secret name'
        required: true
        type: string
      secret_key:
        description: 'JSON key to update (e.g. deployment_settings.docker_image_url)'
        required: true
        type: string
      secret_value:
        description: 'New value for the key'
        required: true
        type: string
      environment:
        description: 'Environment Name'
        required: true
        type: string

jobs:
  update-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: 'google-github-actions/auth@v2'
      with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Update Secret
      run: |
        # Get all active versions
        CURRENT_VERSIONS=$(gcloud secrets versions list "${{ inputs.secret_name }}" --filter="state=enabled" --format="value(name)")

        # Get current secret
        CURRENT_SECRET=$(gcloud secrets versions access latest --secret="${{ inputs.secret_name }}")
        
        # Update specified key using jq
        UPDATED_SECRET=$(echo "$CURRENT_SECRET" | jq --arg new_value "${{ inputs.secret_value }}" --arg key_path "${{ inputs.secret_key }}" 'setpath($key_path | split("."); $new_value)')
        
        # Create new secret version
        echo "$UPDATED_SECRET" | gcloud secrets versions add "${{ inputs.secret_name }}" --data-file=-

        # Disable previous versions
        for VERSION in $CURRENT_VERSIONS; do
          echo "Disabling version $VERSION"
          gcloud secrets versions disable "$VERSION" --secret="${{ inputs.secret_name }}"
        done