name: 'Update HCL'

on:
  workflow_call:
    inputs:
      git_repository:
        required: true
        type: string
      file_location:
        required: true
        type: string
      new_value:
        required: true
        type: string
      key_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      ssh-key:
        required: true


jobs:
  update_terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            repository: ${{ inputs.git_repository }}
            ref: main
            ssh-key: ${{ secrets.ssh-key }}

      - name: Replace input in Terraform file
        run: |
            sed -i 's;${{ inputs.key_name }} .*;${{ inputs.key_name }} = \"${{ inputs.new_value }}\";' ${{ inputs.file_location }}

      - name: Commit changes
        run: |
            git config --global user.name "Integrations Automation"
            git config --global user.email "devops@earthranger.com"
            git add .
            git diff-index --quiet HEAD || git commit -m "Updated ${{ inputs.key_name }} in HCL file"
            git push