name: Update GCP Secret

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'GCP Secret name'
        required: true
        type: string
      secret_key:
        description: 'JSON key to update (e.g. deployment_settings.docker_image_url)'
        required: true
        type: string
      secret_value:
        description: 'New value for the key'
        required: true
        type: string
      project_id:
        description: 'Project ID'
        required: true
        type: string

jobs:
  update-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - uses: 'google-github-actions/auth@v2'
      with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Update Secret
      run: |
        # Get current secret
        CURRENT_SECRET=$(gcloud secrets versions access latest --secret="${{ github.event.inputs.secret_name }}" --project="${{ github.event.inputs.project_id }}")
        
        # Update specified key using jq
        UPDATED_SECRET=$(echo "$CURRENT_SECRET" | jq --arg new_value "${{ github.event.inputs.secret_value }}" --arg key_path "${{ github.event.inputs.secret_key }}" 'setpath($key_path | split("."); $new_value)')
        
        # Create new secret version
        echo "$UPDATED_SECRET" | gcloud secrets versions add "${{ github.event.inputs.secret_name }}" --project="${{ github.event.inputs.project_id }}" --data-file=-